[Feat]: updating the architecture of the ODT document parsing module
normcontrol/normcontrol-Document-Parser pull request #27
Opened 2023-03-11 19:48 UTC by Vl-Tershch

**List of changes:**

- Added methods for printing the contents of objects of unified classes;
- Classes with methods for parsing individual structural elements have been formed;
- Updated scripts with examples of using parsers.

---
**Список изменений:**

- Добавлены методы печати содержимого объектов унифицированных классов;
- Сформированы классы с методами для парсинга отдельных структурных элементов;
- Обновлены скрипты с примерами использования парсеров.

2023-03-11 21:43 UTC, a-berezhkov requested changes

2023-03-11 21:43 UTC, a-berezhkov commented on src/odt/elements/ImagesParser.py
> +        stylesDict = {}
stylesDict не по pip

2023-03-11 21:43 UTC, a-berezhkov commented on src/odt/elements/ImagesParser.py
> +        stylesDict = {}
stylesDict не по pip

2023-03-11 21:43 UTC, a-berezhkov commented on src/odt/elements/ImagesParser.py
> +        help = list(doc.document.element_dict.keys())
Вроде бы `help` зарезервированное слово в python

2023-03-11 21:43 UTC, a-berezhkov commented on src/odt/elements/ImagesParser.py
> +                for i in ast.attributes.keys():
n, i  - непонятно)

2023-03-11 21:43 UTC, a-berezhkov commented on src/odt/elements/ImagesParser.py
> +                for n in ast.attributes.keys():
n, i - непонятно)

2023-03-11 21:43 UTC, a-berezhkov commented on src/odt/elements/ImagesParser.py
> +        objs = doc.document.element_dict.get(token)
Возможно, что функция ничего не вернет

2023-03-11 21:43 UTC, a-berezhkov commented on src/odt/elements/ImagesParser.py
> +    def get_image_parameter(self, doc: ODTDocument, style_name: str, parameter_name: str):
Возможно, что функция ничего не вернет

2023-03-11 21:43 UTC, a-berezhkov commented on src/odt/elements/ListsParser.py
> +        stylesDict = {}
stylesDict

2023-03-11 21:43 UTC, a-berezhkov commented on src/odt/elements/ListsParser.py
> +        stylesDict = {}
stylesDict

2023-03-11 21:43 UTC, a-berezhkov commented on src/odt/elements/ListsParser.py
> +            for n in ast.childNodes:
n

2023-03-11 21:43 UTC, a-berezhkov commented on src/odt/elements/ListsParser.py
> +                        return n.attributes[k]
Может ничего не вернуть функция

2023-03-11 21:43 UTC, a-berezhkov commented on src/odt/elements/NodesParser.py
> +                if (k[1] == "style-name"):
Скобочки

2023-03-11 21:43 UTC, a-berezhkov commented on src/odt/elements/NodesParser.py
> +    def print_all_document_nodes(self, start_node, level=0):
Не совсем понятно, зачем она нужна, кроме отладки. Может в тесты просто вынести эту логику?

2023-03-11 21:43 UTC, a-berezhkov commented on src/odt/elements/NodesParser.py
> +    def print_all_document_nodes_with_higher_style_data(self, start_node, list, doc: ODTDocument, level=0):
ключевое слово list в параметре функции

2023-03-11 21:43 UTC, a-berezhkov commented on src/odt/elements/NodesParser.py
> +                    default2 = consts.DEFAULT_PARAM["font-name"]
default2 - что это?)
и далее по списку )

2023-03-11 21:43 UTC, a-berezhkov commented on src/odt/elements/NodesParser.py
> +    def print_all_document_nodes_with_higher_style_data(self, start_node, list, doc: ODTDocument, level=0):
Какие-то параметры типизированы, а какие-то нет

2023-03-11 21:43 UTC, a-berezhkov commented on src/odt/elements/NodesParser.py
> +        return
Если функция нечего не возвращает, зачем return

2023-03-11 21:43 UTC, a-berezhkov commented on src/odt/elements/ParagraphsParser.py
> +        for n in style.childNodes:
Может ничего не вернуть

2023-03-11 21:43 UTC, a-berezhkov commented on src/odt/elements/ParagraphsParser.py
> +        stylesDict = {}
stylesDict

2023-03-11 21:43 UTC, a-berezhkov commented on src/odt/elements/TablesParser.py
> +        stylesDict = {}
stylesDict

2023-03-11 21:43 UTC, a-berezhkov commented on src/odt/elements/TablesParser.py
> +class TablesParser:
Тут тоже несколько функций, которые могут ничего не вернуть

2023-03-18 13:36 UTC, Vl-Tershch commented on src/odt/elements/AutomaticStylesParser.py
> +from src.odt.elements.ODTDocument import ODTDocument
Исправлено для всех модулей!

2023-03-18 13:36 UTC, Vl-Tershch commented on src/odt/elements/AutomaticStylesParser.py
> +                for k in ast.attributes.keys():
Исправлено для всех модулей!

2023-03-18 13:36 UTC, Vl-Tershch commented on src/odt/elements/AutomaticStylesParser.py
> +            if ast.getAttribute("name") == style_name:
Исправлено для всех модулей!

2023-03-18 13:37 UTC, Vl-Tershch commented on src/odt/elements/AutomaticStylesParser.py
> +    def has_automatic_style_parameter(self, doc: ODTDocument, style, param_name: str, default: str,
Рекомендацию учел, но предлагаю использовать ее на этапе рефакторинга методов.

2023-03-18 13:37 UTC, Vl-Tershch commented on src/odt/elements/AutomaticStylesParser.py
> +    def is_automatic_style(self, doc: ODTDocument, style_name: str, param_name: str, property_type: str,
Рекомендацию учел, но предлагаю использовать ее на этапе рефакторинга методов.

2023-03-18 13:37 UTC, Vl-Tershch commented on src/odt/elements/AutomaticStylesParser.py
> +        else:
👍

2023-03-18 13:38 UTC, Vl-Tershch commented on src/odt/elements/AutomaticStylesParser.py
> +            for n in ast.childNodes:
Исправлено для всех модулей!

2023-03-18 13:38 UTC, Vl-Tershch commented on src/odt/elements/AutomaticStylesParser.py
> +                    for k in ast.attributes.keys():
Исправлено для всех модулей!

2023-03-18 13:38 UTC, Vl-Tershch commented on src/odt/elements/AutomaticStylesParser.py
> +    def get_text_style_by_name(self, doc: ODTDocument, text_name: str):
Возможно, но предлагаю оставить это на этап рефакторинга методов.

2023-03-18 13:40 UTC, Vl-Tershch commented on src/helpers/odt/consts.py
> +    A file with constants for attributes of document elements.
В этом файле хранятся атрибуты, которыми обладают элементы, или которые необходимы для анализа. Одновременно с этим они хранят значения по умолчанию, поскольку не всегда объекты могут содержать необходимые атрибуты.

2023-03-18 13:43 UTC, Vl-Tershch commented on src/helpers/odt/path.py
> +"""
Этот файл содержит функцию, восстанавливающую абсолютный путь, в зависимости от операционной системы устройства, для корректного открытия файла.
Возможно и стоит переименовать файл, однако по названию File, по моему мнению, нельзя определить что происходит в нем. Path выглядит релевантнее.

2023-03-18 13:43 UTC, Vl-Tershch commented on src/odt/elements/DefaultStylesParser.py
> +        stylesDict = {}
Исправлено для всех модулей!

2023-03-18 13:43 UTC, Vl-Tershch commented on src/odt/elements/DefaultStylesParser.py
> +                for n in ast.childNodes:
Исправлено для всех модулей!

2023-03-18 13:43 UTC, Vl-Tershch commented on src/odt/elements/DefaultStylesParser.py
> +                    for n in ast.childNodes:
Исправлено для всех модулей!

2023-03-18 13:44 UTC, Vl-Tershch commented on src/odt/elements/DefaultStylesParser.py
> +        for ast in doc.document.styles.childNodes:
Исправлено для всех модулей!

2023-03-18 13:44 UTC, Vl-Tershch commented on src/odt/elements/DefaultStylesParser.py
> +        for n in style.childNodes:
Исправлено для всех модулей!

2023-03-18 13:44 UTC, Vl-Tershch commented on src/odt/elements/DefaultStylesParser.py
> +    def has_default_parameter(self, doc: ODTDocument, style_parameter: str, family: str, parameter_name: str,
Рекомендацию учел, но предлагаю использовать ее на этапе рефакторинга методов.

2023-03-18 13:45 UTC, Vl-Tershch commented on src/odt/elements/DefaultStylesParser.py
> +    def has_default_parameter(self, doc: ODTDocument, style_parameter: str, family: str, parameter_name: str,
Исправлено для всех модулей!

2023-03-18 13:45 UTC, Vl-Tershch commented on src/odt/elements/ImagesParser.py
> +        stylesDict = {}
Исправлено для всех модулей!

2023-03-18 13:45 UTC, Vl-Tershch commented on src/odt/elements/ImagesParser.py
> +        stylesDict = {}
Исправлено для всех модулей!

2023-03-18 13:45 UTC, Vl-Tershch commented on src/odt/elements/ImagesParser.py
> +        help = list(doc.document.element_dict.keys())
Исправлено!

2023-03-18 13:45 UTC, Vl-Tershch commented on src/odt/elements/ImagesParser.py
> +                for i in ast.attributes.keys():
Исправлено для всех модулей!

2023-03-18 13:45 UTC, Vl-Tershch commented on src/odt/elements/ImagesParser.py
> +                for n in ast.attributes.keys():
Исправлено для всех модулей!

2023-03-18 13:45 UTC, Vl-Tershch commented on src/odt/elements/ImagesParser.py
> +        objs = doc.document.element_dict.get(token)
Исправлено!

2023-03-18 13:46 UTC, Vl-Tershch commented on src/odt/elements/ImagesParser.py
> +    def get_image_parameter(self, doc: ODTDocument, style_name: str, parameter_name: str):
Исправлено!

2023-03-18 13:46 UTC, Vl-Tershch commented on src/odt/elements/ListsParser.py
> +        stylesDict = {}
Исправлено для всех модулей!

2023-03-18 13:46 UTC, Vl-Tershch commented on src/odt/elements/ListsParser.py
> +        stylesDict = {}
Исправлено для всех модулей!

2023-03-18 13:48 UTC, Vl-Tershch commented on src/odt/elements/NodesParser.py
> +                if (k[1] == "style-name"):
Нужны, без них не работает.

2023-03-18 13:48 UTC, Vl-Tershch commented on src/odt/elements/NodesParser.py
> +    def print_all_document_nodes(self, start_node, level=0):
Возможно так и сделаем на следующем этапе!

2023-03-18 13:48 UTC, Vl-Tershch commented on src/odt/elements/NodesParser.py
> +    def print_all_document_nodes_with_higher_style_data(self, start_node, list, doc: ODTDocument, level=0):
Исправлено!

2023-03-18 13:49 UTC, Vl-Tershch commented on src/odt/elements/NodesParser.py
> +                    default2 = consts.DEFAULT_PARAM["font-name"]
Рефакторинг будет проведен разработчиком (@galinalar) на следующем этапе!

2023-03-18 13:49 UTC, Vl-Tershch commented on src/odt/elements/NodesParser.py
> +    def print_all_document_nodes_with_higher_style_data(self, start_node, list, doc: ODTDocument, level=0):
Рефакторинг будет проведен разработчиком (@galinalar) на следующем этапе!

2023-03-18 13:49 UTC, Vl-Tershch commented on src/odt/elements/NodesParser.py
> +        return
Исправлено!

2023-03-18 13:49 UTC, Vl-Tershch commented on src/odt/elements/ParagraphsParser.py
> +        for n in style.childNodes:
Исправлено!

2023-03-18 13:49 UTC, Vl-Tershch commented on src/odt/elements/ParagraphsParser.py
> +        stylesDict = {}
Исправлено!

2023-03-18 13:50 UTC, Vl-Tershch commented on src/odt/elements/TablesParser.py
> +        stylesDict = {}
Исправлено!

2023-03-18 13:50 UTC, Vl-Tershch commented on src/odt/elements/TablesParser.py
> +class TablesParser:
Исправлено!

2023-03-19 08:55 UTC, a-berezhkov approved these changes

2023-03-19 18:05 UTC, galinalar approved these changes

2023-03-19 18:12 UTC, merged

2023-04-10 19:52 UTC, algormx commented on src/odt/elements/AutomaticStylesParser.py
> +    def has_automatic_style_parameter(self, doc: ODTDocument, style, param_name: str, default: str,
def is_automatic_style

2023-04-10 19:52 UTC, algormx commented on src/odt/elements/AutomaticStylesParser.py
> +                    property_type: str):
property_name

2023-04-10 19:52 UTC, algormx commented on src/odt/ODTParser.py
> +from src.odt.elements.TablesParser import TablesParser
Предлагается переименовать парсеры элементов с ElementsParser в ElementParser.

2023-04-10 19:52 UTC, algormx commented on src/odt/elements/AutomaticStylesParser.py
> +    def get_automatic_style_object_by_name(self, doc: ODTDocument, style_name: str):
def get_automatic_style_by_name и указать return value через typing.

2023-04-10 19:52 UTC, algormx commented on src/odt/elements/AutomaticStylesParser.py
> +            param_name - string name of the desired parameter;
Не понятно, что это за параметр.

2023-04-10 19:52 UTC, algormx commented on src/odt/elements/AutomaticStylesParser.py
> +    def is_automatic_style(self, doc: ODTDocument, style_name: str, param_name: str, property_type: str,
Может def get_style_parameter?